[package]
name = "graphics-template"
version = "0.0.1"
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
glutin = "0.22.0-alpha2"
winit = "0.20.0-alpha3"
takeable-option = "0.4"
image = "0.21"

[build-dependencies]
gl_generator = "0.13"