[package]
name = "graphics-template"
version = "0.0.1"
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
glutin = "0.22.0-alpha2"
cgmath = "0.17.0"
rand = "0.7.2"

[build-dependencies]
gl_generator = "0.14.0"